# yaml-language-server: $schema=https://raw.githubusercontent.com/davidborzek/containers/main/package.schema.json
---
name: minio-bucket
semver: true
platforms: ["linux/amd64", "linux/arm64"]
goss:
  entrypoint: bash
  args: -c "tail -f /dev/null"
