# yaml-language-server: $schema=https://raw.githubusercontent.com/davidborzek/containers/main/package.schema.json
---
name: tautulli
semver: true
platforms: ["linux/amd64", "linux/arm64"]
goss:
  type: service
