name: Validate Pull Request

on:
  pull_request:
    branches: ["main"]

jobs:
  changed-packages:
    uses: davidborzek/containers/.github/workflows/changed-packages.yaml@main

  build:
    uses: davidborzek/containers/.github/workflows/build.yaml@main
    needs: ["changed-packages"]
    if: ${{ needs.changed-packages.outputs.changed == 'true' }}
    permissions:
      contents: read
      packages: write
    with:
      limit: ${{ needs.changed-packages.outputs.packages }}
      force: true
      push: false
