name: Scheduled Build

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force rebuild"
        required: false
        default: false
        type: boolean
      limit:
        description: "Limit the packages"
        required: false
        type: string
      push:
        description: "Push packages."
        required: false
        default: true
        type: boolean
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    uses: davidborzek/containers/.github/workflows/build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      limit: ${{ inputs.limit }}
      force: ${{ inputs.force == true }}
      push:  ${{ inputs.push || true }}
